### ISSUE TITLE
Error after upgrading to new version.

### ISSUE THREAD

**Issue by hariroshan** [zth/rescript-relay#329]
Hello,
    I have a mutation query and optimistic response like so,
```graphql
mutation SendForm_SendMessageMutation(
    $input: SendMessageInput!
    $loadThread: Boolean = false
  ) @raw_response_type {
    sendMessage(input: $input) {
      errors {
        key
        message
      }
      message {
        id
        insertedAt
        status
        text
      }
      thread @include(if: $loadThread) {
        __typename
        ... on SingleThread {
          id
        }
        ... on GroupThread {
          id
        }
        ... on BroadcastThread {
          id
        }
      }
    }
  }
```
```rescript
let opt_response: SendMessageMutation.Types.rawResponse_sendMessage_thread = #SingleThread(
              SendMessageMutation.make_rawResponse_sendMessage_thread_SingleThread(
                ~__isNode=#SingleThread,
                ~__typename=#SingleThread,
                ~id=threadId->RescriptRelay.dataIdToString,
              )
            )
// the optimistic response is 
~optimisticResponse=SendMessageMutation.makeOptimisticResponse(
                ~sendMessage=SendMessageMutation.make_rawResponse_sendMessage(
                  ~errors=[],
                  ~message={
                    id: newId->RescriptRelay.dataIdToString,
                    text: field.value,
                    insertedAt: insertedAt,
                    status: #SENT,
                  },
                  ~thread=opt_response,
                  (),
                ),
                (),
              ),

```
Compiled Opt. Response looks like 
```js 
var opt_response = Utils$Tradesimplr.debug({
                NAME: "SingleThread",
                VAL: {
                  __typename: "SingleThread",
                  __isNode: "SingleThread",
                  id: threadId
                }
              });
```
Everything compiles fine. The server responds with the following 
```json
{
    "data": {
        "sendMessage": {
            "errors": [],
            "message": {
                "id": "TWVzc2FnZTo1",
                "insertedAt": "2022-04-15T07:37:43Z",
                "status": "SENT",
                "text": "hello"
            },
            "thread": {
                "__isNode": "SingleThread",
                "__typename": "SingleThread",
                "id": "U2luZ2xlVGhyZWFkOjY="
            }
        }
    }
}
```
But in the console, It reports the following 
```
Warning: Expected `optimisticResponse` to match structure of server response for mutation `SendForm_SendMessageMutation`, please define fields for all of
{
  "sendMessage": {
    "thread": {
      "__typename": "<scalar>",
      "id": "<scalar>"
    }
  }
}
printWarning @ warning.js:30
warning @ warning.js:51
validateMutation @ validateMutation.js:69
commitMutation @ commitMutation.js:70
(anonymous) @ useMutation.js:66
_1 @ curry.js:32
(anonymous) @ SendForm.bs.js:68
app @ curry.js:14
(anonymous) @ SendForm.bs.js:334
commitHookEffectListMount @ react-dom.development.js:22912
commitPassiveMountOnFiber @ react-dom.development.js:24647
commitPassiveMountEffects_complete @ react-dom.development.js:24606
commitPassiveMountEffects_begin @ react-dom.development.js:24593
commitPassiveMountEffects @ react-dom.development.js:24581
flushPassiveEffectsImpl @ react-dom.development.js:26700
flushPassiveEffects @ react-dom.development.js:26653
commitRootImpl @ react-dom.development.js:26604
commitRoot @ react-dom.development.js:26380
performSyncWorkOnRoot @ react-dom.development.js:25830
flushSyncCallbacks @ react-dom.development.js:11776
warning.js:30 
        

Warning: Expected `optimisticResponse` to match structure of server response for mutation `SendForm_SendMessageMutation`, please remove all fields of
{
  "sendMessage": {
    "thread": {
      "NAME": {},
      "VAL": {}
    }
  }
}
printWarning @ warning.js:30
warning @ warning.js:51
validateMutation @ validateMutation.js:70
commitMutation @ commitMutation.js:70
(anonymous) @ useMutation.js:66
_1 @ curry.js:32
(anonymous) @ SendForm.bs.js:68
app @ curry.js:14
(anonymous) @ SendForm.bs.js:334
commitHookEffectListMount @ react-dom.development.js:22912
commitPassiveMountOnFiber @ react-dom.development.js:24647
commitPassiveMountEffects_complete @ react-dom.development.js:24606
commitPassiveMountEffects_begin @ react-dom.development.js:24593
commitPassiveMountEffects @ react-dom.development.js:24581
flushPassiveEffectsImpl @ react-dom.development.js:26700
flushPassiveEffects @ react-dom.development.js:26653
commitRootImpl @ react-dom.development.js:26604
commitRoot @ react-dom.development.js:26380
performSyncWorkOnRoot @ react-dom.development.js:25830
flushSyncCallbacks @ react-dom.development.js:11776
SendForm.bs.js:339 


Error Invariant Violation: RelayResponseNormalizer(): Expected a typename for record `{
  "NAME": "SingleThread",
  "VAL": {
    "__typename": "SingleThread",
    "__isNode": "SingleThread",
    "id": "client:local:1"
  }
}`.
    at invariant (http://localhost:4000/js/simplr.js:115492:15)
    at RelayResponseNormalizer._getRecordType (http://localhost:4000/js/simplr.js:190174:35)
    at RelayResponseNormalizer._normalizeLink (http://localhost:4000/js/simplr.js:190696:123)
    at RelayResponseNormalizer._normalizeField (http://localhost:4000/js/simplr.js:190480:14)
    at RelayResponseNormalizer._traverseSelections (http://localhost:4000/js/simplr.js:190185:16)
    at RelayResponseNormalizer._traverseSelections (http://localhost:4000/js/simplr.js:190193:18)
    at RelayResponseNormalizer._normalizeLink (http://localhost:4000/js/simplr.js:190720:10)
    at RelayResponseNormalizer._normalizeField (http://localhost:4000/js/simplr.js:190480:14)
    at RelayResponseNormalizer._traverseSelections (http://localhost:4000/js/simplr.js:190185:16)
    at RelayResponseNormalizer.normalizeResponse (http://localhost:4000/js/simplr.js:190155:10)
```
Why is this happening. Can you help? Thanks

**Comment by zth** [comment]
Hmmm, this is a bug that was fixed recently. What version are you on?

**Comment by hariroshan** [comment]
@zth Thanks for the quick reply,
These are the versions
```
    "react": "18",
    "react-dom": "18",
    "react-relay": "13.2.0",
    "relay-compiler": "11.0.0",
    "relay-config": "11.0.0",
    "relay-runtime": "13.2.0",
    "rescript": "^9.1.4",
    "rescript-relay": "1.0.0-beta.18"
```
the compiled response 
```js
var opt_response = Utils$Tradesimplr.debug({
                NAME: "SingleThread",
                VAL: {
                  __typename: "SingleThread",
                  __isNode: "SingleThread",
                  id: threadId
                }
              });
```

**Comment by hariroshan** [comment]
I WORKED !!! 😆  Thanks 👍  🥳

**Comment by hariroshan** [comment]
Is the VScode extension for the library updated? I still doesn't recognise `client.schema` where as relay compiler does.

**Comment by hariroshan** [comment]
Can you update the docs in `https://rescript-relay-documentation.vercel.app/docs/getting-started`
`yarn add rescript-relay@1.0.0-beta.18 relay-runtime@13.2.0 react-relay@13.2.0`
to
`yarn add rescript-relay@1.0.0-beta.20 relay-runtime@13.2.0 react-relay@13.2.0`

**Comment by zth** [comment]
@hariroshan very glad it worked! 😃 Yes, sorry for not deploying that yet! Will fix.. Thanks!
